### ISSUE TITLE
Can't complete cluster creation using provider AWS

### ISSUE THREAD

**Issue by bscott** [kubicorn/kubicorn#596]
Tried creating a cluster a few times from different machines and accounts and getting following:

**Creating Cluster:**

```
2018-03-19T00:04:53-07:00 [ℹ]  Updating state store for cluster [bscott-aws]

2018-03-19T00:23:13-07:00 [✖]  Unable to write kubeconfig: Timedout writing kubeconfig
~ $
```

**Getting Config:**

```
~ $ kubicorn getconfig bscott-aws
2018-03-19T00:29:52-07:00 [ℹ]  Selected [fs] state store
2018-03-19T00:29:52-07:00 [ℹ]  Loaded cluster: bscott-aws
2018-03-19T00:29:52-07:00 [ℹ]  Init Cluster
2018-03-19T00:29:52-07:00 [✖]  server pool bscott-aws.master in cluster bscott-aws must have a maximum count greater than 0
```

**Version:**

```
Kubicorn version:  {"Version":"0.0.003","GitCommit":"","BuildDate":"2018-03-19 07:34:07.122665045 +0000 UTC","GOVersion":"go1.10","GOARCH":"amd64","GOOS":"darwin"}
```

**Comment by kris-nova** [comment]
What does your initial configuration file look like?

Also hi 👋

**Comment by bscott** [comment]
@kris-nova Hi!

The output I posted are from the initial Create and Apply commands, the last few lines of output. I can paste the yaml if you like.

**Comment by kris-nova** [comment]
Yes please - just trying to replicate this on my end

**Comment by bscott** [comment]
@kris-nova 

```
ClusterAPI: null
SSH:
  identifier: bscott-aws
  metadata:
    creationTimestamp: null
  name: bscott-aws
  publicKeyData: REDACTED
  publicKeyFingerprint: REDACTED
  publicKeyPath: ~/.ssh/id_rsa.pub
  user: ubuntu
cloud: amazon
kubernetesAPI:
  endpoint: REDACTED
  metadata:
    creationTimestamp: null
  port: "443"
location: us-west-2
metadata:
  creationTimestamp: null
name: bscott-aws
network:
  cidr: 10.0.0.0/16
  identifier: vpc-bae496c3
  internetgw:
    identifier: igw-99f764ff
    metadata:
      creationTimestamp: null
  metadata:
    creationTimestamp: null
    name: bscott-aws
  type: public
serverPools:
- awsconfiguration: {}
  bootstrapScripts:
  - bootstrap/amazon_k8s_ubuntu_16.04_master.sh
  firewalls:
  - identifier: sg-93031fec
    ingressRules:
    - ingressFromPort: "22"
      ingressProtocol: tcp
      ingressSource: 0.0.0.0/0
      ingressToPort: "22"
      metadata:
        creationTimestamp: null
    - ingressFromPort: "443"
      ingressProtocol: tcp
      ingressSource: 0.0.0.0/0
      ingressToPort: "443"
      metadata:
        creationTimestamp: null
    - ingressFromPort: "0"
      ingressProtocol: "-1"
      ingressSource: 10.0.100.0/24
      ingressToPort: "65535"
      metadata:
        creationTimestamp: null
    metadata:
      creationTimestamp: null
    name: bscott-aws.master-external-5aaf60d0-3c6d-7815-9f7a-f4f97093188f
  identifier: bscott-aws.master
  image: ami-79873901
  instanceProfile:
    identifier: AIPAIVPAUCXGE5V4J2UTG
    metadata:
      creationTimestamp: null
    name: bscott-aws-KubicornMasterInstanceProfile
    role:
      metadata:
        creationTimestamp: null
      name: bscott-aws-KubicornMasterRole
      policies:
      - document: "{\n\t\t\t\t\t\t\t\t  \"Version\": \"2012-10-17\",\n\t\t\t\t\t\t\t\t
          \ \"Statement\": [\n\t\t\t\t\t\t\t\t\t {\n\t\t\t\t\t\t\t\t\t\t\"Effect\":
          \"Allow\",\n\t\t\t\t\t\t\t\t\t\t\"Action\": [\n\t\t\t\t\t\t\t\t\t\t   \"ec2:*\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"elasticloadbalancing:*\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:GetAuthorizationToken\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:BatchCheckLayerAvailability\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:GetDownloadUrlForLayer\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:GetRepositoryPolicy\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:DescribeRepositories\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:ListImages\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:BatchGetImage\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"autoscaling:DescribeAutoScalingGroups\",\n\t\t\t\t\t\t\t\t\t\t   \"autoscaling:UpdateAutoScalingGroup\"\n\t\t\t\t\t\t\t\t\t\t],\n\t\t\t\t\t\t\t\t\t\t\"Resource\":
          \"*\"\n\t\t\t\t\t\t\t\t\t }\n\t\t\t\t\t\t\t\t  ]\n\t\t\t\t\t\t\t\t}"
        name: MasterPolicy
  metadata:
    creationTimestamp: null
  name: bscott-aws.master
  size: t2.xlarge
  subnets:
  - cidr: 10.0.0.0/24
    identifier: subnet-c475b38f
    metadata:
      creationTimestamp: null
    name: bscott-aws.master
    zone: us-west-2a
  type: master
- awsconfiguration: {}
  bootstrapScripts:
  - bootstrap/amazon_k8s_ubuntu_16.04_node.sh
  firewalls:
  - identifier: sg-42001c3d
    ingressRules:
    - ingressFromPort: "22"
      ingressProtocol: tcp
      ingressSource: 0.0.0.0/0
      ingressToPort: "22"
      metadata:
        creationTimestamp: null
    - ingressFromPort: "0"
      ingressProtocol: "-1"
      ingressSource: 10.0.0.0/24
      ingressToPort: "65535"
      metadata:
        creationTimestamp: null
    metadata:
      creationTimestamp: null
    name: bscott-aws.node-external-5aaf60d0-1d99-a550-55e1-eb4e89b34c8b
  identifier: bscott-aws.node
  image: ami-79873901
  instanceProfile:
    identifier: AIPAJHUIQCJCNSGMPKARE
    metadata:
      creationTimestamp: null
    name: bscott-aws-KubicornNodeInstanceProfile
    role:
      metadata:
        creationTimestamp: null
      name: bscott-aws-KubicornNodeRole
      policies:
      - document: "{\n\t\t\t\t\t\t\t\t  \"Version\": \"2012-10-17\",\n\t\t\t\t\t\t\t\t
          \ \"Statement\": [\n\t\t\t\t\t\t\t\t\t {\n\t\t\t\t\t\t\t\t\t\t\"Effect\":
          \"Allow\",\n\t\t\t\t\t\t\t\t\t\t\"Action\": [\n\t\t\t\t\t\t\t\t\t\t   \"ec2:Describe*\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ec2:AttachVolume\",\n\t\t\t\t\t\t\t\t\t\t   \"ec2:DetachVolume\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:GetAuthorizationToken\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:BatchCheckLayerAvailability\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:GetDownloadUrlForLayer\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:GetRepositoryPolicy\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:DescribeRepositories\",\n\t\t\t\t\t\t\t\t\t\t   \"ecr:ListImages\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"ecr:BatchGetImage\",\n\t\t\t\t\t\t\t\t\t\t   \"autoscaling:DescribeAutoScalingGroups\",\n\t\t\t\t\t\t\t\t\t\t
          \  \"autoscaling:UpdateAutoScalingGroup\"\n\t\t\t\t\t\t\t\t\t\t],\n\t\t\t\t\t\t\t\t\t\t\"Resource\":
          \"*\"\n\t\t\t\t\t\t\t\t\t }\n\t\t\t\t\t\t\t\t  ]\n\t\t\t\t\t\t\t\t}"
        name: NodePolicy
  metadata:
    creationTimestamp: null
  name: bscott-aws.node
  size: t2.medium
  subnets:
  - cidr: 10.0.100.0/24
    identifier: subnet-b77bdcce
    metadata:
      creationTimestamp: null
    name: bscott-aws.node
    zone: us-west-2b
  type: node
values:
  itemMap:
    INJECTEDMASTER: 10.0.0.57:443
    INJECTEDPORT: "443"
    INJECTEDTOKEN: 607abc.55374800c870c868
  metadata:
    creationTimestamp: null
```
